Feature/linters
Markotweyo/portfolio pull request #1
Opened 2022-04-25 10:45 UTC by Markotweyo

Portfolio project in html/css

2022-04-25 11:09 UTC, zainsadaqat requested changes
# Hello @Markotweyo  😃 😄 

You're doing a great job on your project. We're proud of you. Good job so far! 
# 👏🏻 👏🏻 👏🏻 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [ ] Please use full background as per given figma design

[Required Design]

<img width="303" alt="Screen Shot 2022-04-25 at 4 08 32 PM" src="https://user-images.githubusercontent.com/83048208/165077501-67e2ab72-343d-4dc2-a82b-5af1c6b61956.png">

[Your Background]

<img width="316" alt="Screen Shot 2022-04-25 at 4 08 53 PM" src="https://user-images.githubusercontent.com/83048208/165077553-fc641d0d-5c0c-479e-af05-b79e1ced69c3.png">

_Check the comments under the review._


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-25 11:09 UTC, zainsadaqat commented on index.html
> +                <h1 class="username">I'm Mark, Glad to see you!</h1>
Please use the font family "Poppins" as per requirement for the heading. 👍🏻 
[Your Style]
<img width="236" alt="Screen Shot 2022-04-25 at 4 03 11 PM" src="https://user-images.githubusercontent.com/83048208/165076796-02bf5f77-b894-45b3-8615-75545ebffac8.png">

[Required Syle]
<img width="389" alt="Screen Shot 2022-04-25 at 4 01 47 PM" src="https://user-images.githubusercontent.com/83048208/165076628-aab23070-5892-48a1-950f-060b83535191.png">

2022-04-25 11:09 UTC, zainsadaqat commented on index.html
> +                    I’m a software developer! I can help you build a product, feature or website. Look through some of my work and experience! If you like what you see and have a project you need cod
Please use the font family "Poppins" as per requirement for the paragraph. 👍🏻 

[Font, you used]
<img width="289" alt="Screen Shot 2022-04-25 at 4 03 40 PM" src="https://user-images.githubusercontent.com/83048208/165076856-61333bdc-ceab-4116-b803-457e3b8d4d6e.png">

[Required Font]
<img width="387" alt="Screen Shot 2022-04-25 at 4 04 33 PM" src="https://user-images.githubusercontent.com/83048208/165076975-dfbf9351-b9b5-4e69-8180-7b41a258cb1e.png">

2022-04-25 11:09 UTC, zainsadaqat commented on index.html
> +            <span class="socialmedia">LET'S CONNECT</span>
Please use the font family "Poppins" as per requirement for the subtitle. 👍🏻 

[Font Used]
<img width="149" alt="Screen Shot 2022-04-25 at 4 05 49 PM" src="https://user-images.githubusercontent.com/83048208/165077137-9ae17903-27df-4512-ba77-166e826f6a36.png">


[Font Required]
<img width="154" alt="Screen Shot 2022-04-25 at 4 06 13 PM" src="https://user-images.githubusercontent.com/83048208/165077190-bf931a7b-8fa4-415a-a333-a9ec32d273ce.png">

2022-04-28 14:42 UTC, Markotweyo commented
Hi, I have fixed the background cover image and the "Poppins" font family

2022-04-28 15:02 UTC, Lucas-Masaba approved these changes
# Hello @Markotweyo  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Good job implementing the changes by the previous reviewer 🏄 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 15:02 UTC, Lucas-Masaba commented on index.html
> +            </div>
[OPTIONAL]
- Please remember to place these icons in an `ul` tag with each icon having a `li` tag.

2022-04-28 16:22 UTC, merged